default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: localhost
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: clinic_development